## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

#create the functions from the examples
#instead of getting the mean (as in the example)
##I need to obtain the inverse, so I replace all 'mean' mentions with 'inverse'
##I looked it up and it seems that 'inverse' is a function in R

##this function creates the cache matrix
makeCacheMatrix <- function(x = matrix()) {
inverse<-NULL
set<-function(y=matrix()){
  x<<-y*
  inverse<<-NULL
}
get<-function()x
setinverse<-function(inverse)i<<-inverse
getinverse<-function()i
list(set = set, get = get,
     setinverse=setinverse,
     getinverse=getinverse)
}

##this function solves the inverse of the cached matrix (generated by above function)
cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
      i<-x$getinverse()
  if(!is.null(i)){
    message("getting cached data") 
    return(i)
  }
  mymatrix<-x$get()
  i<-inverse(data,...)
  x$setinverse(i)
  i
}

##now that I have my functions developed, I'm going
##to create a matrix and calculate its inverse to see if it worked.
##I'm assuming I can create any matrix? 

myMatrix<-matrix(1:50, nrow=25, ncol=4)
print(myMatrix)
class(myMatrix)

#from the notes: Computing the inverse of a square matrix can be done with the solve function in R.
diditwork<-solve(myMatrix) 
##nope, my function didn't work, an error message says: 
##"Error in solve.default(myMatrix) : 'a' (25 x 4) must be square"

##I googled the error msg and can see I need to set my matrix dimensions differently
##"verify the matrix whose power you want to take is square"

##let me try 1:16 and 4rows 4cols because these are perfect squares
myMatrix<-matrix(1:16,nrow=4,ncol=4)
print(myMatrix)
class(myMatrix)

diditwork<-solve(myMatrix) 
##new error msg: Error in solve.default(myMatrix) : 
##Lapack routine dgesv: system is exactly singular: U[3,3] = 0

##Googling tells me that this error is occurring because the matrix
##I created is singular and thus cannot be inverted .... 
##so of course I google 'how to transform a singular matrix r inverse'

##what I found is a video from Khan Academy
##that explains how to make a matrix invertible
##the example Khan uses is a 2x2 matrix with variables a.b,c,d
##so I create a similar matrix: 

myMatrix<-matrix(1:4,nrow=2,ncol=2)
diditwork<-solve(myMatrix)
#no error msg came up this time! 
print(diditwork)
##   [,1] [,2]
##[1,]   -2  1.5
##[2,]    1 -0.5

##it worked! calculate the inverse of myMatrix

###now that I have the right matrix, I test it with my functions
myMatrix<-matrix(1:4, nrow=2,ncol=2)
print(myMatrix)
##     [,1] [,2]
##[1,]    1    3
##[2,]    2    4

testmyMatrix<-makeCacheMatrix(myMatrix)
myinverse<-cacheSolve(testmyMatrix)
##Error in x$getinverse(): object 'i' not found

##go back to cacheSolve to fix this error
##i don't understand, I defined 'i' 
##in this code of my makeCacheMatrix function:
#   setinverse<-function(inverse)i<<-inverse
#   getinverse<-function()i

typeof(myMatrix)
##[1]"integer"
typeof(testmyMatrix)
##[1]"list"

##Googling reveals I must convert my matrix to numeric##
myMatrixB<-as.numeric(myMatrix)
testmyMatrix<-makeCacheMatrix(myMatrixB)
myinverse<-cacheSolve(testmyMatrix)
##back to this error: 
##Error in x$getinverse() : object 'i' not found

##maybe try to convert my matrix to a vector?
> vectormyMatrix <- as.vector(myMatrix)
testmyMatrix<-makeCacheMatrix(vectormyMatrix)
##and also my result as a vector:
myInverse<-as.vector(cacheSolve(testmyMatrix))

##returns same error message:
## "Error in x$getinverse() : object 'i' not found"

################################


typeof(makeCacheMatrix)
##[1]"closure"
typeof(cacheSolve)
##[1]"closure

##Google: "A closure in R is an object that contains functions bound 
##to the environment the closure was created in."
##This message means that you have a variable which represents a function, and you're 
##mistakenly using square brackets to try and subset it
##thinking that it represents a data